a = int(input("Enter the first number : "))
b = int(input("Enter the second number : "))
print(f"{a} + {b} = ",(a+b))
print(f"{a} - {b} = ",(a-b))
print(f"{a} * {b} = ",(a*b))
print(f"{a} / {b} = ",(a/b))
print(f"{a} // {b} = ",(a//b))
print(f"{a} % {b} = ",(a%b))